bump browser versions
RedHatQE/selenium-images pull request #9
Opened 2021-04-14 15:33 UTC by digitronik

@quarckster I need chrome only but even I touch firefox
please correct me

2021-04-14 17:29 UTC, quarckster requested changes

2021-04-14 17:29 UTC, quarckster commented on .github/workflows/deploy.yml
> +        firefox_version: ["68.12.0esr", "84.0.2", "78.9.0esr", "87.0"]
Old versions can be dropped:
```
firefox_version: ["68.12.0esr", "78.9.0esr", "87.0"]
```

2021-04-14 17:29 UTC, quarckster commented on .github/workflows/deploy.yml
> +        chrome_version: ["88.0.4324.96", "89.0.4389.128-1"]
Same here
```
chrome_version:  "89.0.4389.128-1"]
```

2021-04-15 06:40 UTC, digitronik commented on .github/workflows/deploy.yml
> +        firefox_version: ["68.12.0esr", "84.0.2", "78.9.0esr", "87.0"]
sure

2021-04-15 06:48 UTC, digitronik commented on .github/workflows/deploy.yml
> +        chrome_version: ["88.0.4324.96", "89.0.4389.128-1"]
@quarckster done

2021-04-15 07:01 UTC, quarckster approved these changes

2021-04-15 07:01 UTC, merged